# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 149db53f9992ba5ecb400c51089a2dc165ab431be31f33d53b399295ec95375c366ca434f412bc9c7d9924a08124c7623bb53ecedd8ac98fd5d6bdf587bfc916

test:
  secret_key_base: 4326c6099363490cafc925ae10e68be852e43175689bdf44c17580f9aaf10206b1d0724b7fe80ef4222a760cb221c4513631f16b7f8d19c79f21dfcfcaa23b16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
